### ISSUE TITLE
Running with a more recent emscripten?

### ISSUE THREAD

**Issue by ChrisJefferson** [mame/xterm-pty#3]
I was trying to use your library to build an emscripten version of gap (github.com/gap-system/gap). It seems to set up mostly well, but input isn't being handled correctly (a newline seems to appear after every character, and full lines don't seem to get sent correctly).

Before I start deeply debugging, I noticed I'm using emscripten 3.1.23, but you mention using the internals of a specific, earlier, version. I need to use a reasonable recent emscripten, as I need some fixes relating to ASYNCIFY functionality. Would you expect the library to work with 3.1.23, or where should I look to see how to make it work?

At present building your own emscripten GAP is very fiddly, I'd be happy to provide it if you want, but I'd probably want to tidy it up a bit first.

**Comment by mame** [comment]
I rebuilt all demos with emscripten 3.1.23.

https://xterm-pty.netlify.app/

<img width="183" alt="image" src="https://user-images.githubusercontent.com/21557/195145677-9a9644d8-4c66-4ddd-9915-236bec5b5a00.png">

Though I had to make [a minor change](https://github.com/mame/xterm-pty/commit/fd2b3bc6caba8505e23a033b62cf9ea70436be3f) to absorb [a trivial incompatibility](https://github.com/emscripten-core/emscripten/pull/15005), looks like all of them work well. 

There may be a bug in the implementation of a terminal feature not used in these demos. If you give me a way to reproduce it, I might look at it sometime.

**Comment by ChrisJefferson** [comment]
I have sent you an email, you of course don't have to look at it. The problem is a built copy of GAP is around 500MB (I hope to reduce that in future!)

**Comment by ChrisJefferson** [comment]
I found the bug, I'm not positive whose fault it is.

The problem is GAP was assuming if it ever calls `read` on fid 0 (when 0 is attached to a TTY), if it gets 0 bytes that means there is no more user input, as normally read will wait for more user input.

This was causing it to stop, which I thought was a problem with xterm-pty. What I'm not sure about is if this "read returning 0" is GAP's incorrect assumption, or emscripten's fault, or xterm-pty's fault.

**Comment by ChrisJefferson** [comment]
Here is a demo of our app. Thanks for the great library! https://chrisjefferson.github.io/gap-web-demo/

**Comment by mame** [comment]
I'm glad you got it working right! How did you deal with the issue?

> What I'm not sure about is if this "read returning 0" is GAP's incorrect assumption, or emscripten's fault, or xterm-pty's fault.

That assumption sounds correct to me. However, if the assumption is simply not met, I don't think that vim would work properly.

Currently, [example.c uses `fread`](https://github.com/mame/xterm-pty/blob/5647d237080cd1a40193366b9a461929b880341a/demo/build/example.c#L21
). I replaced it with `read(0, name, 256)` and it works as expected, i.e., wait for user input. Maybe there are more complicated reproduction conditions.

**Comment by ChrisJefferson** [comment]
I will have a go and see if I can reproduce the problem as a small example. Is there an easy way for me to build the repository + tests? I'm afraid I'm not a npm expert, so sorry if this is obvious.

At the moment, if I get a read of size 0, I just re-read, but that isn't right (read should only return 0 for EOF).

**Comment by ChrisJefferson** [comment]
I managed to find a small example!

In this program, you will get output like the following

```
:1:a:
:0::
:1:b:
:0::
```

Which means I get a character typed, then 0, then a character, then 0. There should never be a read of size 0. I think to get this you need to turn off input buffering, then start reading one character at a time, using `read`.

```
#include <stdio.h>
#include <string.h>
#include <termios.h>
#include <unistd.h>

int main()
{
    char name[256];

    struct termios syOld, syNew; /* old and new terminal state      */

    /* try to get the terminal attributes, will fail if not terminal       */
    const int fd = 0;
    if (tcgetattr(fd, &syOld) == -1)
        return 0;

    /* disable interrupt, quit, start and stop output characters           */
    syNew = syOld;

    /* disable input buffering, line editing and echo                      */
    syNew.c_cc[VMIN] = 1;
    syNew.c_cc[VTIME] = 0;
    syNew.c_lflag &= ~(ECHO | ICANON);

    if (tcsetattr(fd, TCSANOW, &syNew) == -1)
        return 0;
    while (1)
    {
        memset(name, 0, 256);
        int x = read(0, name, 1);
        printf(":%d:%s:\n", x, name);
    }

    return 0;
}

**Comment by mame** [comment]
@ChrisJefferson Thanks! I found a bug in xterm-pty. It did not properly support the read syscall with one-length buffer (i.e., `read(0, buf, 1)`)

I think #4 fixes the issue. I will merge it and release xterm-pty 0.9.4 soon. I'd be happy if you could give it a try without the workaround of double read.
