### ISSUE TITLE
Wrong Tab behaviour.

### ISSUE THREAD

**Issue by utkrssh** [mame/xterm-pty#36]
When I run the example program, I get the prompt `[Echo ON] Input your name: `. I press Tab and then Backspace. The cursor comes well before the point where it should be. While on a standard Linux console the cursor comes to the point where it was before pressing the Tab key.

**Comment by utkrssh** [comment]
For my use, I corrected the behavior by inserting `this.baseColumn=this.column` after the following line.
https://github.com/mame/xterm-pty/blob/cfcbc7e2145d03a0afef45939e3971becb2b4443/src/lineDiscipline.ts#L484

**Comment by mame** [comment]
Thank you. I reproduce the issue.

Curiously, this behavior in question has been tested in lineDiscipline.test.ts and works fine.

https://github.com/mame/xterm-pty/blob/cfcbc7e2145d03a0afef45939e3971becb2b4443/src/lineDiscipline.test.ts#L231-L233

We need to observe the communication with xterm.js and investigate what is different from this test behavior. I think it will take some time.

**Comment by mame** [comment]
Sorry, that was simple. The baseColumn must be updated when input from xterm.js (`writeFromLower`) after the output of the process (`writeFromUpper`). Maybe it is correct to do it after `finishECHOPRT`, so I fixed it that way.

**Comment by mame** [comment]
I have released xterm-pty 0.10.2. Thanks again!
