### ISSUE TITLE
failing to overwrite __syscall_ioctl for ioctl call to select raw mode

### ISSUE THREAD

**Issue by okapia** [mame/xterm-pty#6]
I'm attempting to build zsh with emscripten and using mame/xterm-pty to connect it in with xterm.js. This is largely working but the terminal does not appear to be initialised correctly. It appears to remain in _cooked_ mode so very basic editing only and the line is echoed back after pressing enter. So the code for changing to raw mode fails.

When I try to open the JavaScript inspector, the console tab shows:

```
failed to overwrite __syscall_ioctl of emscripten [workerTools.js:1:1272](https://cdn.jsdelivr.net/npm/xterm-pty@0.9.4/workerTools.js)
failed to overwrite __syscall_newselect of emscripten [workerTools.js:1:1350](https://cdn.jsdelivr.net/npm/xterm-pty@0.9.4/workerTools.js)
TypeError: self.asmLibraryArg is undefined [workerTools.js:1:1418](https://cdn.jsdelivr.net/npm/xterm-pty@0.9.4/workerTools.js)
    emscriptenHack https://cdn.jsdelivr.net/npm/xterm-pty@0.9.4/workerTools.js:1
    onmessage http://localhost:8080/example.worker.js:7
```

Any idea how I can better debug why it should fail to overwrite the ioctl. system call which I think is what is used for selecting raw mode. I get similar results in both Firefox and edge (both on Linux). Could this be due to running a newer emscripten (I have the latest emsdk - 3.1.37). It'd be nice to have some basic build instructions for xterm-pty, I'm no JavaScript programmer so have no idea of the associated tooling. Would be nice to have the option of building myself and adding debug.

Is it possible to use xterm-pty just with a real terminal for testing purposes?

I get that without working fork(), a zsh build is going to have limited utility but it could still be good enough for a demo / tutorial that can be put on the website. I thought I had seen working examples of it (or bash) on websites elsewhere but perhaps they're attaching to actual VMs or emulating more of an actual OS somehow.

**Comment by mame** [comment]
Thanks for trying.

> Could this be due to running a newer emscripten (I have the latest emsdk - 3.1.37).

Maybe this is the case. This library needs to hook system calls such as ioctl, but emscripten does not provide an API to allow us to hook them, so it is achieved by a very version-dependent hack. As README.md says, I confirmed that it worked with Emscripten 2.0.13 which is pretty old. I'll try to update it when I have time.

> Is it possible to use xterm-pty just with a real terminal for testing purposes?

Not so far. It would be useful to have.

**Comment by mame** [comment]
I am not familiar with the JS toolchain neither, but AFAIK, usually, package.json contains a command on how to build it. In short, do `npm install && npm run build` and you will see the output. Note that the files in `out/` are intermediate code. You will find index.js and workerTools.js in the top directory.

I agree that JS toolchain has many unfamiliar conventions and conversions that are tiring. But it is not my fault. Please don't blame me.

Note that simply rebuilding xterm-pty will not make it work with the latest version of emscripten. We need to read the source code of emscripten runtime, devise a hack to hook in, and reimplement emscriptenHack.ts.

**Comment by okapia** [comment]
I don't blame you. And it is by no means unique to the JS toolchain but it just helps to have the basic steps. The two you list are rather easier than what I was doing so thanks for that.

I had done some initial experiments along these lines way back in 2015. At that time I had failed to compile ncurses and wrote a very minimal terminfo library. I was then assuming I'd need to replace further calls in the C. I've just cleaned up that old code and pushed it to https://github.com/okapia/titi/
For anything that doesn't need all of curses, that might be a smaller and simpler option. Zsh builds against it and when built natively rather than with emscripten, it works.

I've briefly looked at what you're doing in the `emscriptenHack.ts` code and it's clear I'll have a lot of reading to do if I'm going to make much sense of it. I've checked that `self.asmLibraryArg` has been removed in emscripten since 2.0.13 which confirms what you say.

Thanks

**Comment by mame** [comment]
@okapia I think #7 should fix this issue. Could you give it a try?

**Comment by okapia** [comment]
Have just given it a try and that does work. Thanks for the fix!

I did get errors telling me to relink with an increased stack size and the newer xtermjs I used seems to fill the full width of the browser window instead of just being 80 characters but that's all unrelated to xterm-pty.

**Comment by mame** [comment]
OK thanks for your confirmation. I will cut a release soon.
