### ISSUE TITLE
Does it support to use emrun to provide the http server?

### ISSUE THREAD

**Issue by versaloon** [mame/xterm-pty#9]
I follow the instructions, and while loading the page, there are errors:

emscriptenHack.ts:201 failed to overwrite __syscall_ioctl of emscripten
e.emscriptenHack @ emscriptenHack.ts:201
emscriptenHack.ts:205 failed to overwrite __syscall_newselect of emscripten
e.emscriptenHack @ emscriptenHack.ts:205
emscriptenHack.ts:208 Uncaught TypeError: Cannot read properties of undefined (reading 'dummy')
    at e.emscriptenHack (emscriptenHack.ts:208:30)
    at onmessage (worker.js:6:3)

**Comment by mame** [comment]
Sorry, it is already fixed at https://github.com/mame/xterm-pty/commit/28dbacb22f6a36bd335186bce3c39d229ef4d457 but not released. I will cut a release later

**Comment by mame** [comment]
Oh, that was already released. Just for case, I have released xterm-pty 0.9.6. If it doesn't work, please send me information on the version of emscripten and xterm-pty that you are using.
